meta:
  engine: 4.2.0

units:
  # promicro/nice nano size
  px: 18
  py: 33

  skt: 19.05

points:
  zones:
    matrix:
      anchor.shift: [50,-100]
      columns:
        pinky:
          key:
            splay: 8
            origin: [0, -17]
            column_net: C0
        ring:
          key:
            stagger: 0.66cy
            splay: -4
            origin: [0, -17]
            column_net: C1
        middle:
          key:
            stagger: 0.25cy
            splay: -4
            origin: [0, -17]
            column_net: C2
        index:
          key:
            stagger: -0.25cy
            origin: [0, -17]
            column_net: C3
        inner:
          key:
            stagger: -0.1cy
            origin: [0, -17]
            column_net: C4
          rows:
            top:
              adjust.rotate: 180
      rows:
        bottom:
          row_net: R2
        home:
          row_net: R1
        top:
          row_net: R0
      key:
        padding: cy
        spread: cx
        width: cx
        height: cy
        tags: 
          - key
        nets:
          colrow: "{{column_net}}_{{row_net}}"
    thumb:
      anchor:
        ref: matrix_index_bottom
        shift: [0.66cx, -1.25cy]
      columns:
        first:
          key:
            splay: -10
            column_net: C4
        second:
          key:
            splay: -15
            origin: [-9, -9.5]
            column_net: C5
      rows:
        only:
          row_net: R3
      key:
        padding: cy
        spread: cx
        width: cx
        height: cy
        tags: 
          - key
        nets:
          colrow: "{{column_net}}_{{row_net}}"

    mcu: &mcu
      anchor:
        ref.aggregate.parts: [matrix_inner_home, matrix_inner_bottom]
        shift: [0.5cx + 10.5, 4]
      key:
        tags:
          - mcu
        height: 0
        width: 0

    tenting_puck: &tent
      anchor:
        ref: matrix_index_home
        shift: [-0.5cx+0.5, 0.5cy-2]
      key:
        tags:
          - tent
        height: 0
        width: 0
    
    screw_top: &screws
      anchor:
        ref: [tenting_puck]
        shift: [0, skt]
      key:
        tags:
          - screws
        height: 0
        width: 0
    screw_left:
      <<: *screws
      anchor:
        ref: [tenting_puck]
        shift: [-skt, 0]
    screw_bottom:
      <<: *screws
      anchor:
        ref: [tenting_puck]
        shift: [0, -skt]
    screw_right:
      <<: *screws
      anchor:
        ref: [tenting_puck]
        shift: [skt, 0]
    
    non_slip_top_left: &non_slip
      anchor:
        ref: matrix_pinky_top
        shift: [-0.25cx, 0.25cy]
      key:
        tags:
          - non_slip
        height: 0
        width: 0
    non_slip_top_middle:
      <<: *non_slip
      anchor:
        ref: matrix_middle_top
        shift: [0, 0.25cy]
    non_slip_top_right: 
      <<: *non_slip
      anchor:
        ref: matrix_inner_top
        shift: [-0.25cx, -0.25cy]
    non_slip_mcu:
      <<: *non_slip
      anchor:
        ref: [mcu]
        shift: [0.5px-0.25cx, 0.5py-0.25cy]
    non_slip_bottom_right: 
      <<: *non_slip
      anchor:
        ref: thumb_second_only
        shift: [0.25cx, -0.25cy]
    non_slip_bottom_middle:
      <<: *non_slip 
      anchor:
        ref: matrix_middle_bottom
        shift: [0, -0.5cy-15]
    non_slip_bottom_left:
      <<: *non_slip
      anchor:
        ref: matrix_pinky_bottom
        shift: [-0.25cx, -0.25cy]
    
    cover_left: &cover
      anchor:
        ref: thumb_second_only
        shift: [-0.5cx+4, 0.5cy+4.5]
      key:
        tags:
          - cover
        height: 0
        width: 0
    cover_right:
      <<: *cover
      anchor:
        ref: thumb_second_only
        shift: [0.5cx-3, 0.5cy+4.5]

outlines:
  _raw:
    - what: rectangle
      where: [key]
      size: [cx, cy]
  _pcb:
    - what: path
      segments:
        - type: arc
          points:
            - ref: matrix_pinky_top
              shift: [-0.5cx, 0.5cy]
            - ref: matrix_ring_top
              shift: [-0.5cx, 0.5cy]
            - ref: matrix_inner_top
              shift: [-0.5cx, -0.5cy]
        - type: line
          points:
            - ref: [mcu]
              shift: [-0.5px - 1.5, 0.5py]
        - type: line
          points:
            - ref: [mcu]
              shift: [0.5px, 0.5py]
        - type: line
          points:
            - ref: thumb_second_only
              shift: [0.5cx, 0.5cy+7.8735]
        - type: line
          points:
            - ref: thumb_second_only
              shift: [0.5cx, -0.5cy]
        - type: arc
          points:
            - ref: thumb_first_only
              shift: [-0.5cx, -0.5cy]
            - ref: matrix_pinky_bottom
              shift: [-0.5cx, -0.5cy]
        - type: line
          points:
            - ref: matrix_pinky_top
              shift: [-0.5cx, 0.5cy]
      expand: 0.5
      fillet: 1
  _wall:
    - name: _pcb
      expand: 1.6
    - operation: subtract
      name: _pcb
  _power_switch:
    - what: rectangle
      where: [mcu]
      size: [10, 7]
      adjust.shift: [0.5px-1.9, -0.5py-5]
  _heat_inserts:
    - what: circle
      where: [screws]
      radius: 2.5
  _heat_inserts_negative:
    - what: circle
      where: [screws]
      radius: 1.5
  _non_slip:
    - what: circle
      where: [non_slip]
      radius: 4.1
  _mcu_cover:
    - what: rectangle
      where: [mcu]
      size: [px, py]
    - what: polygon
      points:
        - ref: [mcu]
          shift: [-0.5px, -0.5py]
        - ref: [mcu]
          shift: [-0.5px, -0.5py-10]
        - ref: thumb_second_only
          shift: [0.5cx, 0.5cy]
        - ref: thumb_second_only
          shift: [0.5cx, 0.5cy+7.8735]
        - ref: [mcu]
          shift: [0.5px, -0.5py]
    - operation: subtract
      what: rectangle
      where.ref: thumb_second_only
      size: [cx, cy]
      adjust.shift: [0, 1.5]
      fillet: 1
    - operation: subtract
      what: circle
      where: [cover]
      radius: 1
pcbs:
  simple34_v2:
    template: kicad8
    outlines.name.outline: _pcb
    footprints:
      mcu:
        what: ceoloide/mcu_supermini_nrf52840
        where: [mcu]
        params:
          reverse_mount: true
          reversible: true
          P21: C0
          P20: C1
          P19: C2
          P18: C3
          P15: C4
          P14: C5
          P9: R3
          P8: R2
          P7: R1
          P6: R0
      choc_hotswap:
        what: ceoloide/switch_choc_v1_v2
        where: [key]
        params:
          from: "{{column_net}}"
          to: "{{colrow}}"
          include_corner_marks: true
          include_keycap: true
          keycap_height: 16.5
          keycap_width: 17.5
          reversible: true
          hotswap: true
          choc_v2_support: false
          outer_pad_width_front: 2.0
          outer_pad_width_back: 2.0
        adjust.rotate: 180
      diode:
        what: ceoloide/diode_tht_sod123
        where: [key]
        params:
          reversible: true
          include_thru_hole_smd_pads: true
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, 4.7]
          rotate: 180
      tenting_puck:
        what: splitkb/tenting_puck
        where: [tenting_puck]
      mounting:
        what: ceoloide/mounting_hole_plated
        where: [cover]
        params:
          drill: 2
          outline: 1
      power_switch:
        what: ceoloide/power_switch_smd_side
        where: [mcu]
        params:
          reversible: true
          include_silkscreen: false
          from: BAT_P
          to: RAW
        adjust:
          shift: [0.5px-1.9, -0.5py-5]
      reset:
        what: terence/reset
        where: [mcu]
        params.reversible: true
        adjust:
          shift: [0, -0.5py-3]
      battery:
        what: ceoloide/battery_connector_jst_ph_2
        where: [mcu]
        params:
          include_silkscreen: false
          include_fabrication: false
          include_courtyard: false
        adjust:
          shift: [-0.5px+2, -0.5py-2]
          rotate: 90
cases:
  left:
    - name: _wall
      extrude: 6.6
      fillet: 0.5
    - name: _pcb
      extrude: 2
    - name: _heat_inserts
      extrude: 2
      shift: [0, 0, 2]
    - operation: subtract
      name: _non_slip
      extrude: 1
    - operation: subtract
      name: _heat_inserts_negative
      extrude: 3
      shift: [0, 0, 1]
    - operation: subtract
      name: _power_switch
      extrude: 2.6
      shift: [0, 0, 4]
  _right:
    - name: _wall
      extrude: 6.6
      fillet: 0.5
    - name: _pcb
      extrude: 2
      shift: [0, 0, 4.6]
    - name: _heat_inserts
      extrude: 2
      shift: [0, 0, 2.6]
    - operation: subtract
      name: _non_slip
      extrude: 1
      shift: [0, 0, 5.6]
    - operation: subtract
      name: _heat_inserts_negative
      extrude: 3
      shift: [0, 0, 2.6]
    - operation: subtract
      name: _power_switch
      extrude: 2.6
  right:
    - what: case
      name: _right
      rotate: [0, 180, 0]
  mcu_cover:
    - name: _mcu_cover
      extrude: 2