# Auto-generated by Ergogen
# Case: left

import cadquery as cq
import math
import pathlib

def make_part_left_0__wall_a():
    edges = []
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(128.345722, -42.232022, 0),
        cq.Vector(78.330333, -35.810581, 0),
        cq.Vector(32.762379, -57.405386, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(32.762379, -57.405386, 0),
        cq.Vector(32.133014, -58.330409, 0),
        cq.Vector(32.014573, -59.442946, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(32.014573, -59.442946, 0),
        cq.Vector(38.973228, -108.956349, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(38.973228, -108.956349, 0),
        cq.Vector(39.832087, -110.446535, 0),
        cq.Vector(41.484347, -110.924368, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(41.484347, -110.924368, 0),
        cq.Vector(89.556785, -111.934969, 0),
        cq.Vector(135.943024, -124.595829, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(135.943024, -124.595829, 0),
        cq.Vector(137.652826, -124.610237, 0),
        cq.Vector(138.899992, -123.440857, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(138.899992, -123.440857, 0),
        cq.Vector(138.900209, -123.440392, 0),
        cq.Vector(138.900426, -123.439928, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(138.900426, -123.439928, 0),
        cq.Vector(148.507499, -102.837494, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(148.507499, -102.837494, 0),
        cq.Vector(148.507715, -102.837029, 0),
        cq.Vector(148.507932, -102.836564, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(148.507932, -102.836564, 0),
        cq.Vector(148.668583, -102.362782, 0),
        cq.Vector(148.722991, -101.865472, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(148.722991, -101.865472, 0),
        cq.Vector(148.722991, -61.808813, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(148.722991, -61.808813, 0),
        cq.Vector(148.049336, -60.182467, 0),
        cq.Vector(146.422991, -59.508813, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(146.422991, -59.508813, 0),
        cq.Vector(129.722991, -59.508813, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(129.722991, -59.508813, 0),
        cq.Vector(129.722991, -44.338813, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(129.722991, -44.338813, 0),
        cq.Vector(129.348125, -43.080298, 0),
        cq.Vector(128.345722, -42.232022, 0)
    ))
    _wire_0 = cq.Wire.assembleEdges(edges)
    _face_0 = cq.Face.makeFromWires(_wire_0)
    _solid_0 = cq.Solid.extrudeLinear(_face_0, cq.Vector(0, 0, 5.6))
    result = cq.Workplane("XY").add(_solid_0)
    return result

def make_part_left_0__wall_b():
    edges = []
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(127.703822, -43.697615, 0),
        cq.Vector(78.581184, -37.390794, 0),
        cq.Vector(33.826595, -58.600142, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(33.826595, -58.600142, 0),
        cq.Vector(33.635050, -58.881671, 0),
        cq.Vector(33.599002, -59.220269, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(33.599002, -59.220269, 0),
        cq.Vector(40.557657, -108.733673, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(40.557657, -108.733673, 0),
        cq.Vector(40.819049, -109.187207, 0),
        cq.Vector(41.321911, -109.332635, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(41.321911, -109.332635, 0),
        cq.Vector(89.785972, -110.351469, 0),
        cq.Vector(136.550099, -123.115471, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(136.550099, -123.115471, 0),
        cq.Vector(137.070775, -123.119863, 0),
        cq.Vector(137.450333, -122.763738, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(137.450333, -122.763738, 0),
        cq.Vector(147.057406, -102.161304, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(147.057406, -102.161304, 0),
        cq.Vector(147.106398, -102.016979, 0),
        cq.Vector(147.122991, -101.865472, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(147.122991, -101.865472, 0),
        cq.Vector(147.122991, -61.808813, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(147.122991, -61.808813, 0),
        cq.Vector(146.917966, -61.313838, 0),
        cq.Vector(146.422991, -61.108813, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(146.422991, -61.108813, 0),
        cq.Vector(128.922991, -61.108813, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(128.922991, -61.108813, 0),
        cq.Vector(128.357305, -60.874498, 0),
        cq.Vector(128.122991, -60.308813, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(128.122991, -60.308813, 0),
        cq.Vector(128.122991, -44.338813, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(128.122991, -44.338813, 0),
        cq.Vector(128.008901, -43.955786, 0),
        cq.Vector(127.703822, -43.697615, 0)
    ))
    _wire_0 = cq.Wire.assembleEdges(edges)
    _face_0 = cq.Face.makeFromWires(_wire_0)
    _solid_0 = cq.Solid.extrudeLinear(_face_0, cq.Vector(0, 0, 5.6))
    result = cq.Workplane("XY").add(_solid_0)
    return result

def make_part_left_0__wall():
    a = make_part_left_0__wall_a()
    b = make_part_left_0__wall_b()
    result = a.cut(b)
    return result

def make_part_left_1__base():
    edges = []
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(127.703822, -43.697615, 0),
        cq.Vector(78.581184, -37.390794, 0),
        cq.Vector(33.826595, -58.600142, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(33.826595, -58.600142, 0),
        cq.Vector(33.635050, -58.881671, 0),
        cq.Vector(33.599002, -59.220269, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(33.599002, -59.220269, 0),
        cq.Vector(40.557657, -108.733673, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(40.557657, -108.733673, 0),
        cq.Vector(40.819049, -109.187207, 0),
        cq.Vector(41.321911, -109.332635, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(41.321911, -109.332635, 0),
        cq.Vector(89.785972, -110.351469, 0),
        cq.Vector(136.550099, -123.115471, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(136.550099, -123.115471, 0),
        cq.Vector(137.070775, -123.119863, 0),
        cq.Vector(137.450333, -122.763738, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(137.450333, -122.763738, 0),
        cq.Vector(147.057406, -102.161304, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(147.057406, -102.161304, 0),
        cq.Vector(147.106398, -102.016979, 0),
        cq.Vector(147.122991, -101.865472, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(147.122991, -101.865472, 0),
        cq.Vector(147.122991, -61.808813, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(147.122991, -61.808813, 0),
        cq.Vector(146.917966, -61.313838, 0),
        cq.Vector(146.422991, -61.108813, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(146.422991, -61.108813, 0),
        cq.Vector(128.922991, -61.108813, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(128.922991, -61.108813, 0),
        cq.Vector(128.357305, -60.874498, 0),
        cq.Vector(128.122991, -60.308813, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(128.122991, -60.308813, 0),
        cq.Vector(128.122991, -44.338813, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(128.122991, -44.338813, 0),
        cq.Vector(128.008901, -43.955786, 0),
        cq.Vector(127.703822, -43.697615, 0)
    ))
    _wire_0 = cq.Wire.assembleEdges(edges)
    _face_0 = cq.Face.makeFromWires(_wire_0)
    _solid_0 = cq.Solid.extrudeLinear(_face_0, cq.Vector(0, 0, 2))
    result = cq.Workplane("XY").add(_solid_0)
    return result

def make_part_left_2__mcu_cutout_a():
    result = cq.Workplane("XY")
    return result

def make_part_left_2__mcu_cutout_b():
    edges = []
    edges.append(cq.Edge.makeLine(
        cq.Vector(129.722991, -78.338813, 0),
        cq.Vector(147.122991, -78.338813, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(147.122991, -78.338813, 0),
        cq.Vector(147.122991, -45.338813, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(147.122991, -45.338813, 0),
        cq.Vector(129.722991, -45.338813, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(129.722991, -45.338813, 0),
        cq.Vector(129.722991, -78.338813, 0)
    ))
    _wire_0 = cq.Wire.assembleEdges(edges)
    _face_0 = cq.Face.makeFromWires(_wire_0)
    _solid_0 = cq.Solid.extrudeLinear(_face_0, cq.Vector(0, 0, 3.6))
    result = cq.Workplane("XY").add(_solid_0)
    return result

def make_part_left_2__mcu_cutout():
    result = make_part_left_2__mcu_cutout_b()
    result = result.translate((0, 0, 2))
    return result

def make_part_left_3__heat_inserts_a():
    result = None
    _s = cq.Workplane("XY").moveTo(93.422991, -42.588813).circle(2.500000).extrude(2)
    result = _s if result is None else result.union(_s)
    _s = cq.Workplane("XY").moveTo(74.372991, -61.638813).circle(2.500000).extrude(2)
    result = _s if result is None else result.union(_s)
    _s = cq.Workplane("XY").moveTo(93.422991, -80.688813).circle(2.500000).extrude(2)
    result = _s if result is None else result.union(_s)
    return result

def make_part_left_3__heat_inserts_b():
    result = None
    _s = cq.Workplane("XY").moveTo(112.472991, -61.638813).circle(2.500000).extrude(2)
    result = _s if result is None else result.union(_s)
    return result

def make_part_left_3__heat_inserts():
    a = make_part_left_3__heat_inserts_a()
    b = make_part_left_3__heat_inserts_b()
    result = a.union(b)
    result = result.translate((0, 0, 2))
    return result

def make_part_left_4__stand_a():
    result = None
    _s = cq.Workplane("XY").moveTo(53.795121, -64.965424).circle(2.000000).extrude(2)
    result = _s if result is None else result.union(_s)
    _s = cq.Workplane("XY").moveTo(58.527006, -98.634539).circle(2.000000).extrude(2)
    result = _s if result is None else result.union(_s)
    _s = cq.Workplane("XY").moveTo(124.635876, -108.298943).circle(2.000000).extrude(2)
    result = _s if result is None else result.union(_s)
    return result

def make_part_left_4__stand_b():
    result = None
    _s = cq.Workplane("XY").moveTo(137.922991, -78.338813).circle(2.000000).extrude(2)
    result = _s if result is None else result.union(_s)
    return result

def make_part_left_4__stand():
    a = make_part_left_4__stand_a()
    b = make_part_left_4__stand_b()
    result = a.union(b)
    result = result.translate((0, 0, 2))
    return result

def make_part_left_5__non_slip_a():
    result = None
    _s = cq.Workplane("XY").moveTo(38.597181, -62.809588).circle(4.100000).extrude(1)
    result = _s if result is None else result.union(_s)
    _s = cq.Workplane("XY").moveTo(83.922991, -42.638813).circle(4.100000).extrude(1)
    result = _s if result is None else result.union(_s)
    _s = cq.Workplane("XY").moveTo(123.672991, -48.588813).circle(4.100000).extrude(1)
    result = _s if result is None else result.union(_s)
    _s = cq.Workplane("XY").moveTo(142.422991, -66.088813).circle(4.100000).extrude(1)
    result = _s if result is None else result.union(_s)
    _s = cq.Workplane("XY").moveTo(135.002082, -117.484433).circle(4.100000).extrude(1)
    result = _s if result is None else result.union(_s)
    _s = cq.Workplane("XY").moveTo(83.922991, -104.388813).circle(4.100000).extrude(1)
    result = _s if result is None else result.union(_s)
    return result

def make_part_left_5__non_slip_b():
    result = None
    _s = cq.Workplane("XY").moveTo(44.442451, -104.400847).circle(4.100000).extrude(1)
    result = _s if result is None else result.union(_s)
    return result

def make_part_left_5__non_slip():
    a = make_part_left_5__non_slip_a()
    b = make_part_left_5__non_slip_b()
    result = a.union(b)
    return result

def make_part_left_6__heat_inserts_negative_a():
    result = None
    _s = cq.Workplane("XY").moveTo(93.422991, -42.588813).circle(1.500000).extrude(3)
    result = _s if result is None else result.union(_s)
    _s = cq.Workplane("XY").moveTo(74.372991, -61.638813).circle(1.500000).extrude(3)
    result = _s if result is None else result.union(_s)
    _s = cq.Workplane("XY").moveTo(93.422991, -80.688813).circle(1.500000).extrude(3)
    result = _s if result is None else result.union(_s)
    return result

def make_part_left_6__heat_inserts_negative_b():
    result = None
    _s = cq.Workplane("XY").moveTo(112.472991, -61.638813).circle(1.500000).extrude(3)
    result = _s if result is None else result.union(_s)
    return result

def make_part_left_6__heat_inserts_negative():
    a = make_part_left_6__heat_inserts_negative_a()
    b = make_part_left_6__heat_inserts_negative_b()
    result = a.union(b)
    result = result.translate((0, 0, 1.2))
    return result

def make_case_left():
    _part_0 = make_part_left_0__wall()
    result = _part_0
    _part_1 = make_part_left_1__base()
    result = result.union(_part_1)
    _part_2 = make_part_left_2__mcu_cutout()
    result = result.cut(_part_2)
    _part_3 = make_part_left_3__heat_inserts()
    result = result.union(_part_3)
    _part_4 = make_part_left_4__stand()
    result = result.union(_part_4)
    _part_5 = make_part_left_5__non_slip()
    result = result.cut(_part_5)
    _part_6 = make_part_left_6__heat_inserts_negative()
    result = result.cut(_part_6)
    return result

def make_case():
    return make_case_left()


if __name__ == "__main__":
    result = make_case()
    output_dir = pathlib.Path(__file__).resolve().parent
    cq.exporters.export(result, str(output_dir / "left.step"))
    cq.exporters.export(result, str(output_dir / "left.stl"))
    print("Done.")