# Auto-generated by Ergogen
# Case: mcu_cover

import cadquery as cq
import math
import pathlib

def _outer_wire_edges(result, selector):
    edges = []
    for face in result.faces(selector).vals():
        edges.extend(face.outerWire().Edges())
    return edges

def _fillet_outer_edges(result, top=0, bottom=0):
    if bottom:
        edges = _outer_wire_edges(result, "<Z")
        if edges:
            result = result.newObject(edges).fillet(bottom)
    if top:
        edges = _outer_wire_edges(result, ">Z")
        if edges:
            result = result.newObject(edges).fillet(top)
    return result

def _chamfer_outer_edges(result, top=0, bottom=0):
    if bottom:
        edges = _outer_wire_edges(result, "<Z")
        if edges:
            result = result.newObject(edges).chamfer(bottom)
    if top:
        edges = _outer_wire_edges(result, ">Z")
        if edges:
            result = result.newObject(edges).chamfer(top)
    return result

def make_part_mcu_cover_0__mcu_cover_a():
    edges = []
    edges.append(cq.Edge.makeLine(
        cq.Vector(148.422991, -90.831364, 0),
        cq.Vector(148.422991, -58.838813, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(148.422991, -58.838813, 0),
        cq.Vector(148.130098, -58.131706, 0),
        cq.Vector(147.422991, -57.838813, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(147.422991, -57.838813, 0),
        cq.Vector(131.422991, -57.838813, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(131.422991, -57.838813, 0),
        cq.Vector(130.715884, -58.131706, 0),
        cq.Vector(130.422991, -58.838813, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(130.422991, -58.838813, 0),
        cq.Vector(130.422991, -99.540651, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(130.422991, -99.540651, 0),
        cq.Vector(130.579599, -100.077951, 0),
        cq.Vector(131.000373, -100.446959, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(131.000373, -100.446959, 0),
        cq.Vector(144.664891, -106.818828, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(144.664891, -106.818828, 0),
        cq.Vector(145.429530, -106.852213, 0),
        cq.Vector(145.993818, -106.335139, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(145.993818, -106.335139, 0),
        cq.Vector(148.174360, -101.658950, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(148.174360, -101.658950, 0),
        cq.Vector(148.242710, -101.460034, 0),
        cq.Vector(148.267941, -101.251221, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(148.267941, -101.251221, 0),
        cq.Vector(148.422880, -90.846254, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(148.422880, -90.846254, 0),
        cq.Vector(148.422963, -90.838809, 0),
        cq.Vector(148.422991, -90.831364, 0)
    ))
    _wire_0 = cq.Wire.assembleEdges(edges)
    _face_0 = cq.Face.makeFromWires(_wire_0)
    _solid_0 = cq.Solid.extrudeLinear(_face_0, cq.Vector(0, 0, 2))
    result = cq.Workplane("XY").add(_solid_0)
    result = result.cut(cq.Workplane("XY").moveTo(134.150745, -98.605868).circle(1.000000).extrude(2))
    return result

def make_part_mcu_cover_0__mcu_cover_b():
    result = None
    _s = cq.Workplane("XY").moveTo(144.120131, -103.254669).circle(1.000000).extrude(2)
    result = _s if result is None else result.union(_s)
    return result

def make_part_mcu_cover_0__mcu_cover():
    a = make_part_mcu_cover_0__mcu_cover_a()
    b = make_part_mcu_cover_0__mcu_cover_b()
    result = a.cut(b)
    return result

def make_case_mcu_cover():
    _part_0 = make_part_mcu_cover_0__mcu_cover()
    result = _part_0
    return result

def make_case():
    return make_case_mcu_cover()


if __name__ == "__main__":
    result = make_case()
    output_dir = pathlib.Path(__file__).resolve().parent
    cq.exporters.export(result, str(output_dir / "mcu_cover.step"))
    cq.exporters.export(result, str(output_dir / "mcu_cover.stl"))
    print("Done.")