# Auto-generated by Ergogen
# Case: right

import cadquery as cq
import math
import pathlib

def _outer_wire_edges(result, selector):
    edges = []
    for face in result.faces(selector).vals():
        edges.extend(face.outerWire().Edges())
    return edges

def _inner_wire_edges(result, selector):
    edges = []
    for face in result.faces(selector).vals():
        for wire in face.innerWires():
            edges.extend(wire.Edges())
    return edges

def _apply_edge_treatment(result, part_name, operation_name, operation, outer_top=0, outer_bottom=0, inner_top=0, inner_bottom=0):
    for selector, outer_value, inner_value in (("<Z", outer_bottom, inner_bottom), (">Z", outer_top, inner_top)):
        if outer_value:
            edges = _outer_wire_edges(result, selector)
            if edges:
                try:
                    result = operation(result.newObject(edges), outer_value)
                except Exception as exc:
                    raise RuntimeError(f"{operation_name} failed on {part_name} outer {selector} edges with value {outer_value}") from exc
        if inner_value:
            edges = _inner_wire_edges(result, selector)
            if edges:
                try:
                    result = operation(result.newObject(edges), inner_value)
                except Exception as exc:
                    raise RuntimeError(f"{operation_name} failed on {part_name} inner {selector} edges with value {inner_value}") from exc
    return result

def _fillet_edges(result, part_name, outer_top=0, outer_bottom=0, inner_top=0, inner_bottom=0):
    return _apply_edge_treatment(result, part_name, "fillet", lambda edges, value: edges.fillet(value), outer_top, outer_bottom, inner_top, inner_bottom)

def _chamfer_edges(result, part_name, outer_top=0, outer_bottom=0, inner_top=0, inner_bottom=0):
    return _apply_edge_treatment(result, part_name, "chamfer", lambda edges, value: edges.chamfer(value), outer_top, outer_bottom, inner_top, inner_bottom)

def make_part__right_0__wall_a():
    edges = []
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(129.957481, -42.284590, 0),
        cq.Vector(78.104551, -34.139784, 0),
        cq.Vector(31.196097, -57.689756, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(31.196097, -57.689756, 0),
        cq.Vector(30.629164, -58.591368, 0),
        cq.Vector(30.529171, -59.651706, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(30.529171, -59.651706, 0),
        cq.Vector(37.626999, -110.155377, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(37.626999, -110.155377, 0),
        cq.Vector(38.492248, -111.650552, 0),
        cq.Vector(40.154244, -112.121693, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(40.154244, -112.121693, 0),
        cq.Vector(89.398765, -112.985952, 0),
        cq.Vector(136.864651, -126.129758, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(136.864651, -126.129758, 0),
        cq.Vector(138.582360, -126.153314, 0),
        cq.Vector(139.837269, -124.980163, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(139.837269, -124.980163, 0),
        cq.Vector(150.507499, -102.097782, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(150.507499, -102.097782, 0),
        cq.Vector(150.668472, -101.623571, 0),
        cq.Vector(150.722991, -101.125760, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(150.722991, -101.125760, 0),
        cq.Vector(150.722991, -57.838813, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(150.722991, -57.838813, 0),
        cq.Vector(150.049336, -56.212467, 0),
        cq.Vector(148.422991, -55.538813, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(148.422991, -55.538813, 0),
        cq.Vector(131.222991, -55.538813, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(131.222991, -55.538813, 0),
        cq.Vector(131.222991, -44.338813, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(131.222991, -44.338813, 0),
        cq.Vector(130.881221, -43.132440, 0),
        cq.Vector(129.957481, -42.284590, 0)
    ))
    _wire_0 = cq.Wire.assembleEdges(edges)
    _face_0 = cq.Face.makeFromWires(_wire_0)
    _solid_0 = cq.Solid.extrudeLinear(_face_0, cq.Vector(0, 0, 6.6))
    result = cq.Workplane("XY").add(_solid_0)
    return result

def make_part__right_0__wall_b():
    edges = []
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(129.237725, -43.713559, 0),
        cq.Vector(78.351149, -35.720666, 0),
        cq.Vector(32.316578, -58.831914, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(32.316578, -58.831914, 0),
        cq.Vector(32.144033, -59.106317, 0),
        cq.Vector(32.113600, -59.429029, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(32.113600, -59.429029, 0),
        cq.Vector(39.211428, -109.932700, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(39.211428, -109.932700, 0),
        cq.Vector(39.474765, -110.387754, 0),
        cq.Vector(39.980590, -110.531144, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(39.980590, -110.531144, 0),
        cq.Vector(89.628125, -111.402477, 0),
        cq.Vector(137.482467, -124.653850, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(137.482467, -124.653850, 0),
        cq.Vector(138.005248, -124.661019, 0),
        cq.Vector(138.387177, -124.303974, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(138.387177, -124.303974, 0),
        cq.Vector(149.057406, -101.421593, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(149.057406, -101.421593, 0),
        cq.Vector(149.106398, -101.277268, 0),
        cq.Vector(149.122991, -101.125760, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(149.122991, -101.125760, 0),
        cq.Vector(149.122991, -57.838813, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(149.122991, -57.838813, 0),
        cq.Vector(148.917966, -57.343838, 0),
        cq.Vector(148.422991, -57.138813, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(148.422991, -57.138813, 0),
        cq.Vector(130.422991, -57.138813, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(130.422991, -57.138813, 0),
        cq.Vector(129.857305, -56.904498, 0),
        cq.Vector(129.622991, -56.338813, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(129.622991, -56.338813, 0),
        cq.Vector(129.622991, -44.338813, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(129.622991, -44.338813, 0),
        cq.Vector(129.518941, -43.971603, 0),
        cq.Vector(129.237725, -43.713559, 0)
    ))
    _wire_0 = cq.Wire.assembleEdges(edges)
    _face_0 = cq.Face.makeFromWires(_wire_0)
    _solid_0 = cq.Solid.extrudeLinear(_face_0, cq.Vector(0, 0, 6.6))
    result = cq.Workplane("XY").add(_solid_0)
    return result

def make_part__right_0__wall():
    a = make_part__right_0__wall_a()
    b = make_part__right_0__wall_b()
    result = a.cut(b)
    return result

def make_part__right_1__base():
    edges = []
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(129.237725, -43.713559, 0),
        cq.Vector(78.351149, -35.720666, 0),
        cq.Vector(32.316578, -58.831914, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(32.316578, -58.831914, 0),
        cq.Vector(32.144033, -59.106317, 0),
        cq.Vector(32.113600, -59.429029, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(32.113600, -59.429029, 0),
        cq.Vector(39.211428, -109.932700, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(39.211428, -109.932700, 0),
        cq.Vector(39.474765, -110.387754, 0),
        cq.Vector(39.980590, -110.531144, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(39.980590, -110.531144, 0),
        cq.Vector(89.628125, -111.402477, 0),
        cq.Vector(137.482467, -124.653850, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(137.482467, -124.653850, 0),
        cq.Vector(138.005248, -124.661019, 0),
        cq.Vector(138.387177, -124.303974, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(138.387177, -124.303974, 0),
        cq.Vector(149.057406, -101.421593, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(149.057406, -101.421593, 0),
        cq.Vector(149.106398, -101.277268, 0),
        cq.Vector(149.122991, -101.125760, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(149.122991, -101.125760, 0),
        cq.Vector(149.122991, -57.838813, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(149.122991, -57.838813, 0),
        cq.Vector(148.917966, -57.343838, 0),
        cq.Vector(148.422991, -57.138813, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(148.422991, -57.138813, 0),
        cq.Vector(130.422991, -57.138813, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(130.422991, -57.138813, 0),
        cq.Vector(129.857305, -56.904498, 0),
        cq.Vector(129.622991, -56.338813, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(129.622991, -56.338813, 0),
        cq.Vector(129.622991, -44.338813, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(129.622991, -44.338813, 0),
        cq.Vector(129.518941, -43.971603, 0),
        cq.Vector(129.237725, -43.713559, 0)
    ))
    _wire_0 = cq.Wire.assembleEdges(edges)
    _face_0 = cq.Face.makeFromWires(_wire_0)
    _solid_0 = cq.Solid.extrudeLinear(_face_0, cq.Vector(0, 0, 2))
    result = cq.Workplane("XY").add(_solid_0)
    result = result.translate((0, 0, 4.6))
    return result

def make_part__right_2__heat_inserts_a():
    result = None
    _s = cq.Workplane("XY").moveTo(93.422991, -42.588813).circle(2.500000).extrude(2)
    result = _s if result is None else result.union(_s)
    _s = cq.Workplane("XY").moveTo(74.372991, -61.638813).circle(2.500000).extrude(2)
    result = _s if result is None else result.union(_s)
    _s = cq.Workplane("XY").moveTo(93.422991, -80.688813).circle(2.500000).extrude(2)
    result = _s if result is None else result.union(_s)
    return result

def make_part__right_2__heat_inserts_b():
    result = None
    _s = cq.Workplane("XY").moveTo(112.472991, -61.638813).circle(2.500000).extrude(2)
    result = _s if result is None else result.union(_s)
    return result

def make_part__right_2__heat_inserts():
    a = make_part__right_2__heat_inserts_a()
    b = make_part__right_2__heat_inserts_b()
    result = a.union(b)
    result = result.translate((0, 0, 2.6))
    return result

def make_part__right_3__non_slip_a():
    result = None
    _s = cq.Workplane("XY").moveTo(37.854480, -62.913968).circle(4.100000).extrude(1)
    result = _s if result is None else result.union(_s)
    _s = cq.Workplane("XY").moveTo(83.922991, -42.638813).circle(4.100000).extrude(1)
    result = _s if result is None else result.union(_s)
    _s = cq.Workplane("XY").moveTo(124.422991, -48.588813).circle(4.100000).extrude(1)
    result = _s if result is None else result.union(_s)
    _s = cq.Workplane("XY").moveTo(143.922991, -62.088813).circle(4.100000).extrude(1)
    result = _s if result is None else result.union(_s)
    _s = cq.Workplane("XY").moveTo(135.470504, -118.254551).circle(4.100000).extrude(1)
    result = _s if result is None else result.union(_s)
    _s = cq.Workplane("XY").moveTo(83.922991, -104.388813).circle(4.100000).extrude(1)
    result = _s if result is None else result.union(_s)
    return result

def make_part__right_3__non_slip_b():
    result = None
    _s = cq.Workplane("XY").moveTo(43.769337, -105.000361).circle(4.100000).extrude(1)
    result = _s if result is None else result.union(_s)
    return result

def make_part__right_3__non_slip():
    a = make_part__right_3__non_slip_a()
    b = make_part__right_3__non_slip_b()
    result = a.union(b)
    result = result.translate((0, 0, 5.6))
    return result

def make_part__right_4__heat_inserts_negative_a():
    result = None
    _s = cq.Workplane("XY").moveTo(93.422991, -42.588813).circle(1.500000).extrude(3)
    result = _s if result is None else result.union(_s)
    _s = cq.Workplane("XY").moveTo(74.372991, -61.638813).circle(1.500000).extrude(3)
    result = _s if result is None else result.union(_s)
    _s = cq.Workplane("XY").moveTo(93.422991, -80.688813).circle(1.500000).extrude(3)
    result = _s if result is None else result.union(_s)
    return result

def make_part__right_4__heat_inserts_negative_b():
    result = None
    _s = cq.Workplane("XY").moveTo(112.472991, -61.638813).circle(1.500000).extrude(3)
    result = _s if result is None else result.union(_s)
    return result

def make_part__right_4__heat_inserts_negative():
    a = make_part__right_4__heat_inserts_negative_a()
    b = make_part__right_4__heat_inserts_negative_b()
    result = a.union(b)
    result = result.translate((0, 0, 2.6))
    return result

def make_part__right_5__power_switch_a():
    result = cq.Workplane("XY")
    return result

def make_part__right_5__power_switch_b():
    edges = []
    edges.append(cq.Edge.makeLine(
        cq.Vector(141.522991, -99.338813, 0),
        cq.Vector(151.522991, -99.338813, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(151.522991, -99.338813, 0),
        cq.Vector(151.522991, -92.338813, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(151.522991, -92.338813, 0),
        cq.Vector(141.522991, -92.338813, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(141.522991, -92.338813, 0),
        cq.Vector(141.522991, -99.338813, 0)
    ))
    _wire_0 = cq.Wire.assembleEdges(edges)
    _face_0 = cq.Face.makeFromWires(_wire_0)
    _solid_0 = cq.Solid.extrudeLinear(_face_0, cq.Vector(0, 0, 1.6))
    result = cq.Workplane("XY").add(_solid_0)
    return result

def make_part__right_5__power_switch():
    result = make_part__right_5__power_switch_b()
    return result

def make_case__right():
    _part_0 = make_part__right_0__wall()
    _part_0 = _fillet_edges(_part_0, "_part_0", 0.5, 1, 0, 0)
    result = _part_0
    _part_1 = make_part__right_1__base()
    result = result.union(_part_1)
    _part_2 = make_part__right_2__heat_inserts()
    result = result.union(_part_2)
    _part_3 = make_part__right_3__non_slip()
    result = result.cut(_part_3)
    _part_4 = make_part__right_4__heat_inserts_negative()
    result = result.cut(_part_4)
    _part_5 = make_part__right_5__power_switch()
    result = result.cut(_part_5)
    return result

def make_case_right():
    _part_0 = make_case__right()
    _part_0 = _part_0.rotate((0,0,0),(0,1,0),180)
    result = _part_0
    return result

def make_case():
    return make_case_right()


if __name__ == "__main__":
    result = make_case()
    output_dir = pathlib.Path(__file__).resolve().parent
    cq.exporters.export(result, str(output_dir / "right.step"))
    cq.exporters.export(result, str(output_dir / "right.stl"))
    print("Done.")