# Auto-generated by Ergogen
# Case: right

import cadquery as cq
import math
import pathlib

def _outer_wire_edges(result, selector):
    edges = []
    for face in result.faces(selector).vals():
        edges.extend(face.outerWire().Edges())
    return edges

def _fillet_outer_edges(result, top=0, bottom=0):
    if bottom:
        edges = _outer_wire_edges(result, "<Z")
        if edges:
            result = result.newObject(edges).fillet(bottom)
    if top:
        edges = _outer_wire_edges(result, ">Z")
        if edges:
            result = result.newObject(edges).fillet(top)
    return result

def _chamfer_outer_edges(result, top=0, bottom=0):
    if bottom:
        edges = _outer_wire_edges(result, "<Z")
        if edges:
            result = result.newObject(edges).chamfer(bottom)
    if top:
        edges = _outer_wire_edges(result, ">Z")
        if edges:
            result = result.newObject(edges).chamfer(top)
    return result

def make_part__right_0__wall_a():
    edges = []
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(129.867193, -42.463051, 0),
        cq.Vector(78.135206, -34.337420, 0),
        cq.Vector(31.336157, -57.832526, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(31.336157, -57.832526, 0),
        cq.Vector(30.818523, -58.655736, 0),
        cq.Vector(30.727225, -59.623871, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(30.727225, -59.623871, 0),
        cq.Vector(37.825053, -110.127542, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(37.825053, -110.127542, 0),
        cq.Vector(38.615062, -111.492702, 0),
        cq.Vector(40.132537, -111.922874, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(40.132537, -111.922874, 0),
        cq.Vector(89.427664, -112.788051, 0),
        cq.Vector(136.941878, -125.945269, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(136.941878, -125.945269, 0),
        cq.Vector(138.510221, -125.966777, 0),
        cq.Vector(139.656008, -124.895639, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(139.656008, -124.895639, 0),
        cq.Vector(150.168003, -102.352592, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(150.168003, -102.352592, 0),
        cq.Vector(150.314151, -101.923335, 0),
        cq.Vector(150.364743, -101.472711, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(150.364743, -101.472711, 0),
        cq.Vector(150.522977, -57.846429, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(150.522977, -57.846429, 0),
        cq.Vector(149.910606, -56.356584, 0),
        cq.Vector(148.422991, -55.738813, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(148.422991, -55.738813, 0),
        cq.Vector(131.022991, -55.738813, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(131.022991, -55.738813, 0),
        cq.Vector(131.022991, -44.338813, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(131.022991, -44.338813, 0),
        cq.Vector(130.710842, -43.237183, 0),
        cq.Vector(129.867193, -42.463051, 0)
    ))
    _wire_0 = cq.Wire.assembleEdges(edges)
    _face_0 = cq.Face.makeFromWires(_wire_0)
    _solid_0 = cq.Solid.extrudeLinear(_face_0, cq.Vector(0, 0, 6.6))
    result = cq.Workplane("XY").add(_solid_0)
    return result

def make_part__right_0__wall_b():
    edges = []
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(129.147801, -43.892203, 0),
        cq.Vector(78.382066, -35.918262, 0),
        cq.Vector(32.456638, -58.974684, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(32.456638, -58.974684, 0),
        cq.Vector(32.333392, -59.170686, 0),
        cq.Vector(32.311654, -59.401194, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(32.311654, -59.401194, 0),
        cq.Vector(39.409482, -109.904866, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(39.409482, -109.904866, 0),
        cq.Vector(39.597579, -110.229904, 0),
        cq.Vector(39.958883, -110.332326, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(39.958883, -110.332326, 0),
        cq.Vector(89.656795, -111.204542, 0),
        cq.Vector(137.559694, -124.469362, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(137.559694, -124.469362, 0),
        cq.Vector(137.933109, -124.474483, 0),
        cq.Vector(138.205915, -124.219450, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(138.205915, -124.219450, 0),
        cq.Vector(148.717911, -101.676403, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(148.717911, -101.676403, 0),
        cq.Vector(148.752708, -101.574199, 0),
        cq.Vector(148.764754, -101.466908, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(148.764754, -101.466908, 0),
        cq.Vector(148.922988, -57.840626, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(148.922988, -57.840626, 0),
        cq.Vector(148.777185, -57.485901, 0),
        cq.Vector(148.422991, -57.338813, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(148.422991, -57.338813, 0),
        cq.Vector(130.422991, -57.338813, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(130.422991, -57.338813, 0),
        cq.Vector(129.715884, -57.045919, 0),
        cq.Vector(129.422991, -56.338813, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(129.422991, -56.338813, 0),
        cq.Vector(129.422991, -44.338813, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(129.422991, -44.338813, 0),
        cq.Vector(129.348670, -44.076520, 0),
        cq.Vector(129.147801, -43.892203, 0)
    ))
    _wire_0 = cq.Wire.assembleEdges(edges)
    _face_0 = cq.Face.makeFromWires(_wire_0)
    _solid_0 = cq.Solid.extrudeLinear(_face_0, cq.Vector(0, 0, 6.6))
    result = cq.Workplane("XY").add(_solid_0)
    return result

def make_part__right_0__wall():
    a = make_part__right_0__wall_a()
    b = make_part__right_0__wall_b()
    result = a.cut(b)
    return result

def make_part__right_1__pcb():
    edges = []
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(129.147801, -43.892203, 0),
        cq.Vector(78.382066, -35.918262, 0),
        cq.Vector(32.456638, -58.974684, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(32.456638, -58.974684, 0),
        cq.Vector(32.333392, -59.170686, 0),
        cq.Vector(32.311654, -59.401194, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(32.311654, -59.401194, 0),
        cq.Vector(39.409482, -109.904866, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(39.409482, -109.904866, 0),
        cq.Vector(39.597579, -110.229904, 0),
        cq.Vector(39.958883, -110.332326, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(39.958883, -110.332326, 0),
        cq.Vector(89.656795, -111.204542, 0),
        cq.Vector(137.559694, -124.469362, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(137.559694, -124.469362, 0),
        cq.Vector(137.933109, -124.474483, 0),
        cq.Vector(138.205915, -124.219450, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(138.205915, -124.219450, 0),
        cq.Vector(148.717911, -101.676403, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(148.717911, -101.676403, 0),
        cq.Vector(148.752708, -101.574199, 0),
        cq.Vector(148.764754, -101.466908, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(148.764754, -101.466908, 0),
        cq.Vector(148.922988, -57.840626, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(148.922988, -57.840626, 0),
        cq.Vector(148.777185, -57.485901, 0),
        cq.Vector(148.422991, -57.338813, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(148.422991, -57.338813, 0),
        cq.Vector(130.422991, -57.338813, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(130.422991, -57.338813, 0),
        cq.Vector(129.715884, -57.045919, 0),
        cq.Vector(129.422991, -56.338813, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(129.422991, -56.338813, 0),
        cq.Vector(129.422991, -44.338813, 0)
    ))
    edges.append(cq.Edge.makeThreePointArc(
        cq.Vector(129.422991, -44.338813, 0),
        cq.Vector(129.348670, -44.076520, 0),
        cq.Vector(129.147801, -43.892203, 0)
    ))
    _wire_0 = cq.Wire.assembleEdges(edges)
    _face_0 = cq.Face.makeFromWires(_wire_0)
    _solid_0 = cq.Solid.extrudeLinear(_face_0, cq.Vector(0, 0, 2))
    result = cq.Workplane("XY").add(_solid_0)
    result = result.translate((0, 0, 4.6))
    return result

def make_part__right_2__heat_inserts_a():
    result = None
    _s = cq.Workplane("XY").moveTo(93.422991, -42.588813).circle(2.500000).extrude(2)
    result = _s if result is None else result.union(_s)
    _s = cq.Workplane("XY").moveTo(74.372991, -61.638813).circle(2.500000).extrude(2)
    result = _s if result is None else result.union(_s)
    _s = cq.Workplane("XY").moveTo(93.422991, -80.688813).circle(2.500000).extrude(2)
    result = _s if result is None else result.union(_s)
    return result

def make_part__right_2__heat_inserts_b():
    result = None
    _s = cq.Workplane("XY").moveTo(112.472991, -61.638813).circle(2.500000).extrude(2)
    result = _s if result is None else result.union(_s)
    return result

def make_part__right_2__heat_inserts():
    a = make_part__right_2__heat_inserts_a()
    b = make_part__right_2__heat_inserts_b()
    result = a.union(b)
    result = result.translate((0, 0, 2.6))
    return result

def make_part__right_3__non_slip_a():
    result = None
    _s = cq.Workplane("XY").moveTo(37.854480, -62.913968).circle(4.100000).extrude(1)
    result = _s if result is None else result.union(_s)
    _s = cq.Workplane("XY").moveTo(83.922991, -42.638813).circle(4.100000).extrude(1)
    result = _s if result is None else result.union(_s)
    _s = cq.Workplane("XY").moveTo(124.422991, -48.588813).circle(4.100000).extrude(1)
    result = _s if result is None else result.union(_s)
    _s = cq.Workplane("XY").moveTo(143.922991, -62.088813).circle(4.100000).extrude(1)
    result = _s if result is None else result.union(_s)
    _s = cq.Workplane("XY").moveTo(135.470504, -118.254551).circle(4.100000).extrude(1)
    result = _s if result is None else result.union(_s)
    _s = cq.Workplane("XY").moveTo(83.922991, -104.388813).circle(4.100000).extrude(1)
    result = _s if result is None else result.union(_s)
    return result

def make_part__right_3__non_slip_b():
    result = None
    _s = cq.Workplane("XY").moveTo(43.769337, -105.000361).circle(4.100000).extrude(1)
    result = _s if result is None else result.union(_s)
    return result

def make_part__right_3__non_slip():
    a = make_part__right_3__non_slip_a()
    b = make_part__right_3__non_slip_b()
    result = a.union(b)
    result = result.translate((0, 0, 5.6))
    return result

def make_part__right_4__heat_inserts_negative_a():
    result = None
    _s = cq.Workplane("XY").moveTo(93.422991, -42.588813).circle(1.500000).extrude(3)
    result = _s if result is None else result.union(_s)
    _s = cq.Workplane("XY").moveTo(74.372991, -61.638813).circle(1.500000).extrude(3)
    result = _s if result is None else result.union(_s)
    _s = cq.Workplane("XY").moveTo(93.422991, -80.688813).circle(1.500000).extrude(3)
    result = _s if result is None else result.union(_s)
    return result

def make_part__right_4__heat_inserts_negative_b():
    result = None
    _s = cq.Workplane("XY").moveTo(112.472991, -61.638813).circle(1.500000).extrude(3)
    result = _s if result is None else result.union(_s)
    return result

def make_part__right_4__heat_inserts_negative():
    a = make_part__right_4__heat_inserts_negative_a()
    b = make_part__right_4__heat_inserts_negative_b()
    result = a.union(b)
    result = result.translate((0, 0, 2.6))
    return result

def make_part__right_5__power_switch_a():
    result = cq.Workplane("XY")
    return result

def make_part__right_5__power_switch_b():
    edges = []
    edges.append(cq.Edge.makeLine(
        cq.Vector(141.522991, -99.338813, 0),
        cq.Vector(151.522991, -99.338813, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(151.522991, -99.338813, 0),
        cq.Vector(151.522991, -92.338813, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(151.522991, -92.338813, 0),
        cq.Vector(141.522991, -92.338813, 0)
    ))
    edges.append(cq.Edge.makeLine(
        cq.Vector(141.522991, -92.338813, 0),
        cq.Vector(141.522991, -99.338813, 0)
    ))
    _wire_0 = cq.Wire.assembleEdges(edges)
    _face_0 = cq.Face.makeFromWires(_wire_0)
    _solid_0 = cq.Solid.extrudeLinear(_face_0, cq.Vector(0, 0, 2.6))
    result = cq.Workplane("XY").add(_solid_0)
    return result

def make_part__right_5__power_switch():
    result = make_part__right_5__power_switch_b()
    return result

def make_case__right():
    _part_0 = make_part__right_0__wall()
    _part_0 = _fillet_outer_edges(_part_0, 0.5, 0.5)
    result = _part_0
    _part_1 = make_part__right_1__pcb()
    result = result.union(_part_1)
    _part_2 = make_part__right_2__heat_inserts()
    result = result.union(_part_2)
    _part_3 = make_part__right_3__non_slip()
    result = result.cut(_part_3)
    _part_4 = make_part__right_4__heat_inserts_negative()
    result = result.cut(_part_4)
    _part_5 = make_part__right_5__power_switch()
    result = result.cut(_part_5)
    return result

def make_case_right():
    _part_0 = make_case__right()
    _part_0 = _part_0.rotate((0,0,0),(0,1,0),180)
    result = _part_0
    return result

def make_case():
    return make_case_right()


if __name__ == "__main__":
    result = make_case()
    output_dir = pathlib.Path(__file__).resolve().parent
    cq.exporters.export(result, str(output_dir / "right.step"))
    cq.exporters.export(result, str(output_dir / "right.stl"))
    print("Done.")